core/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, CheckoutView, add_to_cart, remove_from_cart, OrderSummaryView, \
    remove_single_item_from_cart, PaymentView, AddCouponView, RequestRefundView

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/<slug>', ItemDetailView.as_view(), name='products'),
    path('add_to_cart/<slug>', add_to_cart, name='add_to_cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove_from_cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-item-from-cart/<slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>', PaymentView.as_view(), name="payment"),
    path('request-refund', RequestRefundView.as_view(), name="request-refund")
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.urls import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('Sw', 'Sport Wear'),
    ('Ow', 'Out Wear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:products", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name="shipping_address", on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    billing_address = models.ForeignKey(
        'Address', related_name="billing_address", on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    payment = models.ForeignKey(
        'payment', on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    coupon = models.ForeignKey(
        'coupon', on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          {% include "order_snippet.html" %}

          <!-- Promo code -->
          <form class="card p-2" action="{% url 'core:add-coupon' %}" method="post">
              {% csrf_token %}
            <div class="input-group">
<!--              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">-->
                {{ couponform.code }}
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}

templates/home.html
{% extends 'base.html' %}

 {% block head_title %}
  Ecommerce
{% endblock head_title %}

  {% block content %}

  <!--Carousel Wrapper-->
<!--  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">-->

<!--    &lt;!&ndash;Indicators&ndash;&gt;-->
<!--    <ol class="carousel-indicators">-->
<!--      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>-->
<!--      <li data-target="#carousel-example-1z" data-slide-to="1"></li>-->
<!--      <li data-target="#carousel-example-1z" data-slide-to="2"></li>-->
<!--    </ol>-->
    <!--/.Indicators-->

<!--    &lt;!&ndash;Slides&ndash;&gt;-->
<!--    <div class="carousel-inner" role="listbox">-->

<!--      &lt;!&ndash;First slide&ndash;&gt;-->
<!--      <div class="carousel-item active">-->
<!--        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">-->

<!--          &lt;!&ndash; Mask & flexbox options&ndash;&gt;-->
<!--          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">-->

<!--            &lt;!&ndash; Content &ndash;&gt;-->
<!--            <div class="text-center white-text mx-5 wow fadeIn">-->
<!--              <h1 class="mb-4">-->
<!--                <strong>Learn Bootstrap 4 with MDB</strong>-->
<!--              </h1>-->

<!--              <p>-->
<!--                <strong>Best & free guide of responsive web design</strong>-->
<!--              </p>-->

<!--              <p class="mb-4 d-none d-md-block">-->
<!--                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and-->
<!--                  written versions-->
<!--                  available. Create your own, stunning website.</strong>-->
<!--              </p>-->

<!--              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start-->
<!--                free tutorial-->
<!--                <i class="fas fa-graduation-cap ml-2"></i>-->
<!--              </a>-->
<!--            </div>-->
<!--            &lt;!&ndash; Content &ndash;&gt;-->

<!--          </div>-->
<!--          &lt;!&ndash; Mask & flexbox options&ndash;&gt;-->

<!--        </div>-->
<!--      </div>-->
<!--      &lt;!&ndash;/First slide&ndash;&gt;-->

<!--      &lt;!&ndash;Second slide&ndash;&gt;-->
<!--      <div class="carousel-item">-->
<!--        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">-->

<!--          &lt;!&ndash; Mask & flexbox options&ndash;&gt;-->
<!--          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">-->

<!--            &lt;!&ndash; Content &ndash;&gt;-->
<!--            <div class="text-center white-text mx-5 wow fadeIn">-->
<!--              <h1 class="mb-4">-->
<!--                <strong>Learn Bootstrap 4 with MDB</strong>-->
<!--              </h1>-->

<!--              <p>-->
<!--                <strong>Best & free guide of responsive web design</strong>-->
<!--              </p>-->

<!--              <p class="mb-4 d-none d-md-block">-->
<!--                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and-->
<!--                  written versions-->
<!--                  available. Create your own, stunning website.</strong>-->
<!--              </p>-->

<!--              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start-->
<!--                free tutorial-->
<!--                <i class="fas fa-graduation-cap ml-2"></i>-->
<!--              </a>-->
<!--            </div>-->
<!--            &lt;!&ndash; Content &ndash;&gt;-->

<!--          </div>-->
<!--          &lt;!&ndash; Mask & flexbox options&ndash;&gt;-->

<!--        </div>-->
<!--      </div>-->
<!--      &lt;!&ndash;/Second slide&ndash;&gt;-->

<!--      &lt;!&ndash;Third slide&ndash;&gt;-->
<!--      <div class="carousel-item">-->
<!--        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">-->

<!--          &lt;!&ndash; Mask & flexbox options&ndash;&gt;-->
<!--          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">-->

<!--            &lt;!&ndash; Content &ndash;&gt;-->
<!--            <div class="text-center white-text mx-5 wow fadeIn">-->
<!--              <h1 class="mb-4">-->
<!--                <strong>Learn Bootstrap 4 with MDB</strong>-->
<!--              </h1>-->

<!--              <p>-->
<!--                <strong>Best & free guide of responsive web design</strong>-->
<!--              </p>-->

<!--              <p class="mb-4 d-none d-md-block">-->
<!--                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and-->
<!--                  written versions-->
<!--                  available. Create your own, stunning website.</strong>-->
<!--              </p>-->

<!--              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start-->
<!--                free tutorial-->
<!--                <i class="fas fa-graduation-cap ml-2"></i>-->
<!--              </a>-->
<!--            </div>-->
<!--            &lt;!&ndash; Content &ndash;&gt;-->

<!--          </div>-->
<!--          &lt;!&ndash; Mask & flexbox options&ndash;&gt;-->

<!--        </div>-->
<!--      </div>-->
<!--      &lt;!&ndash;/Third slide&ndash;&gt;-->

<!--    </div>-->
<!--    &lt;!&ndash;/.Slides&ndash;&gt;-->

<!--    &lt;!&ndash;Controls&ndash;&gt;-->
<!--    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">-->
<!--      <span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
<!--      <span class="sr-only">Previous</span>-->
<!--    </a>-->
<!--    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">-->
<!--      <span class="carousel-control-next-icon" aria-hidden="true"></span>-->
<!--      <span class="sr-only">Next</span>-->
<!--    </a>-->
<!--    &lt;!&ndash;/.Controls&ndash;&gt;-->

<!--  </div>-->
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
<!--                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"-->
<!--                  alt="">-->
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                    {% if item.discount_price %}
                    {{ item.discount_price }}$
                    {% else %}
                    {{ item.price }}$
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/item_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Here is the list of items</h2>

{% for item in items %}
{{ item.title }} - {{item.price}}
{% endfor %}

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %} <!--for updating cart number dynamically-->

<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Ecommerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link waves-effect" href="/">Home-->
<!--              <span class="sr-only">(current)</span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link waves-effect" href="/checkout">Checkout</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link waves-effect" href="/products">Products</a>-->
<!--          </li>-->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                <span class="clearfix d-none d-sm-inline-block"> Logout </span>
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                <span class="clearfix d-none d-sm-inline-block"> Login </span>
              </a>
            </li>
          <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                <span class="clearfix d-none d-sm-inline-block"> Signup </span>
              </a>
            </li>
          {% endif %}

        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/request_refund.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

  {% block content %}

  <!--Main layout-->
  <main>
    <div class="container">
        <h2>Request Refund</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
  </main>
  <!--Main layout-->

{% endblock content %}